# Python officielle
FROM python:3.8-slim-buster

#répertoire de travail
WORKDIR /app

#dépendances de l'application
COPY requirements.txt .

#  les dépendances
RUN pip install --no-cache-dir -r requirements.txt

#  le contenu de l'application
COPY . .


